### ISSUE TITLE
break up calc_concentration_response.R into individual functions

### ISSUE THREAD

**Issue by Spatiotemporal-Exposures-and-Toxicology** [Spatiotemporal-Exposures-and-Toxicology/GeoToxPackage#24]

**Comment by Spatiotemporal-Exposures-and-Toxicology** [comment]
@SkylarMarvel Was looking to write tests for calc_concentration_response.R and am thinking individual functions for GCA/IA response and HQ would be cleaner. Is there a major reason to keep it as one big one?

**Comment by SkylarMarvel** [comment]
@Spatiotemporal-Exposures-and-Toxicology They all use the same input values for Ci, tp and AC50, so having them all computed at the same time makes sense. Also, some of the downstream functions expect the currently output data.frame with multiple fits. If desired, we could add flags for computing only certain values, but I would avoid splitting it into multiple functions.

**Comment by Spatiotemporal-Exposures-and-Toxicology** [comment]
@SkylarMarvel Ok, that makes sense. No need for flags atm. I will close this issue then.
